CREATE TABLE [dbo].[Metadata]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [FileId] UNIQUEIDENTIFIER NOT NULL REFERENCES [dbo].[File], 
    [Key] NVARCHAR(255) NOT NULL, 
    [Value] NVARCHAR(MAX) NOT NULL
)
